---
title: "CompoundDb"
author: "Mar Garcia-Aloy"
output: 
  BiocStyle::html_document:
    toc: false
    number_sections: false
    toc_float: false
---

https://rformassspectrometry.github.io/CompoundDb/articles/create-compounddb.html#compdb-from-custom-data

```{r, include=FALSE}
startpoint <- Sys.time()
```

# Libraries

```{r, message=FALSE}
library(CompoundDb)
library(MetaboCoreUtils)
```


# Main code

```{r}
cmps <- read.csv("TS8.csv")
cmps <- cmps[cmps$Adduct != "", ]
colnames(cmps) <- c("RT", "mz", "metabolite", "ion_mode", "conf_level", "formula", "adduct")

# Create the dataframe with the necessary data from each compound
cmps <- data.frame(
  compound_id = paste0(
    "C", formatC(seq(nrow(cmps)), width = nchar(nrow(cmps)), flag = "0")),
  name = cmps$metabolite,
  inchi = NA_character_,
  inchikey = NA_character_,
  formula = cmps$formula,
  exactmass = NA,
  rtime = cmps$RT,
  synonyms = NA_character_,
  adduct = cmps$adduct
)


# Calculate exact masses:
for(i in seq(nrow(cmps))){
    cmps$exactmass[i] <- calculateMass(cmps$formula[i])
}

# Create "metadata":
metad <- make_metadata(source = "inhouse", url = "",
                       source_version = "0", 
                       source_date = Sys.Date(),
                       organism = NA_character_)

# Create "CompDb":
db_file <- createCompDb(cmps, metadata = metad, 
                        path = getwd(), dbFile = "CompDb_inhouse_0.sqlite")
(cdb <- CompDb(db_file, flags = RSQLite::SQLITE_RW))


# Create "IonDb":
idb <- IonDb(cdb)
for(i in seq(nrow(cmps))){
  x <- unlist(strsplit(cmps$adduct[i], "; "))
  ion <- data.frame(
    compound_id = rep(cmps$compound_id[i], length(x)),
    ion_adduct = x,
    ion_mz = rep(NA, length(x)),
    ion_rt = rep(cmps$rtime[i], length(x))
  )
  for(j in seq(nrow(ion))){
    ion$ion_mz[j] <- mass2mz(cmps$exactmass[i], x[j])
  }
  ion$ion_rt <- as.numeric(ion$ion_rt)*60
  idb <- insertIon(idb, ion)
}

# Save the output
ionsdb <- ions(idb, c(
  "compound_id", "name", "ion_adduct", "ion_mz", "ion_rt"))
save(ionsdb, file = "ionsdb.RData")
```


# Session info

```{r}
Sys.time()-startpoint
devtools::session_info()
```
